version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: make node_modules
      - run:
          name: Build
          command: PATH=$PATH:~/bin make build
