version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: make node_modules
      - run:
          name: Download fonts
          command: make src/retro8.ttf src/retro16.ttf
      - run:
          name: Build
          command: PATH=$PATH:~/bin make build
